sync_folder: data
mount_commands:
  - at: catalog
    folder: src/alienbio/catalog
  - at: fixtures
    folder: tests/fixtures
  - at: fixtures
    module: tests.fixtures
  - at: alienbio
    module: alienbio
